[window]
opacity = 0.5
blur = true

[colors.primary]
background = "#000000"

[[keyboard.bindings]]
key = "W"
mods = "Control|Shift"
action = "Quit"



[[keyboard.bindings]]
key = "J"
mods = "Control|Shift"
action = "ScrollLineDown"

[[keyboard.bindings]]
key = "K"
mods = "Control|Shift"
action = "ScrollLineUp"

[[keyboard.bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[keyboard.bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[keyboard.bindings]]
key = "A"
mods = "Control|Shift"
action = "ToggleViMode"

# Delete word to the left with Ctrl+Backspace
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"
